kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: managed-velero-operator
  namespace: openshift-velero
subjects:
- kind: ServiceAccount
  name: managed-velero-operator
  namespace: openshift-velero
roleRef:
  kind: ClusterRole
  name: managed-velero-operator
  apiGroup: rbac.authorization.k8s.io
